-- MySQL Script generated by MySQL Workbench
-- Thu Oct  8 17:57:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OCPizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OCPizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OCPizza` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
USE `OCPizza` ;

-- -----------------------------------------------------
-- Table `OCPizza`.`Pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Pizzeria` (
  `pizzeria_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `shortDescription` VARCHAR(100) NOT NULL,
  `imageName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pizzeria_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `OCPizza`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_number` INT NULL,
  `date` DATETIME NULL,
  `amount` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `is_paid` TINYINT NULL,
  `withdrawal` VARCHAR(45) NULL,
  `Pizzeria_pizzeria_id` INT NOT NULL,
  PRIMARY KEY (`order_id`, `Pizzeria_pizzeria_id`),
  INDEX `fk_Order_Pizzeria1_idx` (`Pizzeria_pizzeria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Pizzeria1`
    FOREIGN KEY (`Pizzeria_pizzeria_id`)
    REFERENCES `OCPizza`.`Pizzeria` (`pizzeria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Invoice` (
  `invoice_id` INT NOT NULL AUTO_INCREMENT,
  `invoice_number` INT NULL,
  `payment_date` DATETIME NULL,
  `payment_mode` VARCHAR(40) NULL,
  `Order_order_id` INT NOT NULL,
  PRIMARY KEY (`invoice_id`),
  INDEX `fk_Invoice_Order1_idx` (`Order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Invoice_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `OCPizza`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NOT NULL,
  `additional_information` VARCHAR(255) NULL,
  `postal_code` INT NOT NULL,
  `city` VARCHAR(50) NOT NULL,
  `phone_number` INT(20) NOT NULL,
  `latitude` FLOAT NULL,
  `longitude` FLOAT NULL,
  `is_default_address` TINYINT NULL,
  `Pizzeria_pizzeria_id` INT NOT NULL,
  PRIMARY KEY (`address_id`, `Pizzeria_pizzeria_id`),
  INDEX `fk_Address_Pizzeria1_idx` (`Pizzeria_pizzeria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Pizzeria1`
    FOREIGN KEY (`Pizzeria_pizzeria_id`)
    REFERENCES `OCPizza`.`Pizzeria` (`pizzeria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `account_number` VARCHAR(100) NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `birthday` DATETIME NULL,
  `email` VARCHAR(100) NULL,
  `login` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `token` VARCHAR(100) NULL,
  `Address_address_id` INT NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_Customer_Address1_idx` (`Address_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_Customer_Address1`
    FOREIGN KEY (`Address_address_id`)
    REFERENCES `OCPizza`.`Address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `account_status` INT NULL,
  `first_name` VARCHAR(50) NULL,
  `last_name` VARCHAR(50) NULL,
  `birthday` DATETIME NULL,
  `email` VARCHAR(100) NULL,
  `login` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `token` VARCHAR(100) NULL,
  `Pizzeria_pizzeria_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `Pizzeria_pizzeria_id`),
  INDEX `fk_Employee_Pizzeria1_idx` (`Pizzeria_pizzeria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Pizzeria1`
    FOREIGN KEY (`Pizzeria_pizzeria_id`)
    REFERENCES `OCPizza`.`Pizzeria` (`pizzeria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Menu` (
  `menu_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(255) NULL,
  `image_ name` VARCHAR(45) NULL,
  `price` DECIMAL(10) NULL,
  PRIMARY KEY (`menu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(255) NULL,
  `image_name` VARCHAR(45) NULL,
  `price` DECIMAL(10) NULL,
  PRIMARY KEY (`item_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(255) NULL,
  `image_name` VARCHAR(45) NULL,
  `parent_category_id` INT NOT NULL,
  PRIMARY KEY (`category_id`),
  INDEX `fk_parent_category_idx` (`parent_category_id` ASC) VISIBLE,
  CONSTRAINT `fk_parent_category`
    FOREIGN KEY (`parent_category_id`)
    REFERENCES `OCPizza`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`CategoryHasItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`CategoryHasItem` (
  `category_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`category_id`, `item_id`),
  INDEX `fk_Category_has_Item_Item1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_Category_has_Item_Category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category_has_Item_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `OCPizza`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_item_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `OCPizza`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Note` (
  `item_id` INT NOT NULL,
  `description` INT NOT NULL,
  CONSTRAINT `fk_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `OCPizza`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Recipe` (
  `item_id` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `preparation_time_in_seconds` INT NULL,
  INDEX `fk_item_id_idx` (`item_id` ASC) VISIBLE,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `fk_item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `OCPizza`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Ingredient` (
  `ingredient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(255) NULL,
  `price` DECIMAL(10) NULL,
  PRIMARY KEY (`ingredient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`EmployeeHasRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`EmployeeHasRole` (
  `Role_role_id` INT NOT NULL,
  `Employee_employee_id` INT NOT NULL,
  PRIMARY KEY (`Role_role_id`, `Employee_employee_id`),
  INDEX `fk_Role_has_Employee_Employee1_idx` (`Employee_employee_id` ASC) VISIBLE,
  INDEX `fk_Role_has_Employee_Role1_idx` (`Role_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_Role_has_Employee_Role1`
    FOREIGN KEY (`Role_role_id`)
    REFERENCES `OCPizza`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_has_Employee_Employee1`
    FOREIGN KEY (`Employee_employee_id`)
    REFERENCES `OCPizza`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`OrderHasMenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`OrderHasMenu` (
  `Order_order_id` INT NOT NULL,
  `Menu_menu_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`Order_order_id`, `Menu_menu_id`),
  INDEX `fk_Order_has_Menu_Menu1_idx` (`Menu_menu_id` ASC) VISIBLE,
  INDEX `fk_Order_has_Menu_Order1_idx` (`Order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Menu_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `OCPizza`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Menu_Menu1`
    FOREIGN KEY (`Menu_menu_id`)
    REFERENCES `OCPizza`.`Menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`RecipeHasIngredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`RecipeHasIngredient` (
  `Recipe_item_id` INT NOT NULL,
  `Ingredient_ingredient_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`Recipe_item_id`, `Ingredient_ingredient_id`),
  CONSTRAINT `fk_Recipe_has_Ingredient_Ingredient1`
    FOREIGN KEY (`Recipe_item_id` , `Ingredient_ingredient_id`)
    REFERENCES `OCPizza`.`Ingredient` (`ingredient_id` , `ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recipe_has_Ingredient_Recipe`
    FOREIGN KEY (`Recipe_item_id`)
    REFERENCES `OCPizza`.`Recipe` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`Stock` (
  `Ingredient_ingredient_id` INT NOT NULL,
  `Pizzeria_pizzeria_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`Ingredient_ingredient_id`, `Pizzeria_pizzeria_id`),
  INDEX `fk_Ingredient_has_Pizzeria_Pizzeria1_idx` (`Pizzeria_pizzeria_id` ASC) VISIBLE,
  INDEX `fk_Ingredient_has_Pizzeria_Ingredient1_idx` (`Ingredient_ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredient_has_Pizzeria_Ingredient1`
    FOREIGN KEY (`Ingredient_ingredient_id`)
    REFERENCES `OCPizza`.`Ingredient` (`ingredient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredient_has_Pizzeria_Pizzeria1`
    FOREIGN KEY (`Pizzeria_pizzeria_id`)
    REFERENCES `OCPizza`.`Pizzeria` (`pizzeria_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`MenuHasItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`MenuHasItem` (
  `Item_item_id` INT NOT NULL,
  `Menu_menu_id` INT NOT NULL,
  PRIMARY KEY (`Item_item_id`, `Menu_menu_id`),
  INDEX `fk_Item_has_Menu_Menu1_idx` (`Menu_menu_id` ASC) VISIBLE,
  INDEX `fk_Item_has_Menu_Item1_idx` (`Item_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_has_Menu_Item1`
    FOREIGN KEY (`Item_item_id`)
    REFERENCES `OCPizza`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Menu_Menu1`
    FOREIGN KEY (`Menu_menu_id`)
    REFERENCES `OCPizza`.`Menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OCPizza`.`OrderHasItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OCPizza`.`OrderHasItem` (
  `Order_order_id` INT NOT NULL,
  `Item_item_id` INT NOT NULL,
  PRIMARY KEY (`Order_order_id`, `Item_item_id`),
  INDEX `fk_Order_has_Item_Item1_idx` (`Item_item_id` ASC) VISIBLE,
  INDEX `fk_Order_has_Item_Order1_idx` (`Order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_has_Item_Order1`
    FOREIGN KEY (`Order_order_id`)
    REFERENCES `OCPizza`.`Order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Item_Item1`
    FOREIGN KEY (`Item_item_id`)
    REFERENCES `OCPizza`.`Item` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
